import 'package:drift/drift.dart';

import '../theme/area_palette.dart';
import '../time/calendar_date.dart';
import 'app_database.steps.dart';
import 'converters.dart';
import 'enums.dart';
import 'ids.dart';
import 'tables.dart';

export 'package:drift/drift.dart' show Value;

export 'enums.dart';
export '../time/calendar_date.dart';

part 'app_database.drift.dart';

@DriftDatabase(
  tables: [
    Areas,
    Objectives,
    KeyResults,
    Projects,
    Tasks,
    Habits,
    HabitChecks,
    LogEntries,
    WeeklyReviews,
    Settings,
  ],
)
class AppDatabase extends _$AppDatabase {
  AppDatabase(super.executor);

  @override
  int get schemaVersion => 2;

  @override
  MigrationStrategy get migration => MigrationStrategy(
    onCreate: (m) async {
      await m.createAll();
      await _seedDefaultAreas();
    },
    // Generated by `dart run drift_dev make-migrations`; one step per
    // version, tested in test/core/db/migrations/.
    onUpgrade: stepByStep(
      // v2: local settings.
      from1To2: (m, schema) => m.createTable(schema.settings),
    ),
  );

  /// Runs once, when the database file is created.
  Future<void> _seedDefaultAreas() async {
    final now = DateTime.now().toUtc();
    await batch((batch) {
      for (final (index, area) in defaultAreas.indexed) {
        batch.insert(
          areas,
          AreasCompanion.insert(
            id: uuidV4(),
            createdAt: now,
            updatedAt: now,
            name: area.name,
            color: area.color,
            sortOrder: index,
          ),
        );
      }
    });
  }
}
